import React from 'react';
import { ArrowLeft, Code2, BookOpen, Terminal, AlertCircle } from 'lucide-react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import './RecursiveDescent.css';

const RecursiveDescent = () => {
    return (
        <div className="rd-unit-container">
            <div className="rd-workspace-header">
                <motion.h2 initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
                    <Link to="/unit2-3" className="rd-back-link" title="Back to Syntax Unit">
                        <ArrowLeft size={24} />
                    </Link>
                    <Code2 size={28} className="rd-header-icon" />
                    Recursive Descent Parsing
                </motion.h2>
                <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.15 }}>
                    A top-down parsing technique where each non-terminal in the grammar has a corresponding procedure (function) that recognizes strings generated by that non-terminal.
                </motion.p>
            </div>

            <div className="rd-main-grid">
                {/* Definition & Example Grammar */}
                <motion.div
                    className="rd-definition-card"
                    initial={{ opacity: 0, y: 24 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                >
                    <div className="rd-section-title">
                        <div className="rd-section-icon">
                            <BookOpen size={22} />
                        </div>
                        Recursive Descent Parsing
                    </div>
                    <p className="rd-definition-text">
                        Consider <span className="rd-em">RHS of any production rule</span> as definition of the procedure.
                        Each non-terminal becomes a procedure, and each terminal in the RHS is matched against the current lookahead token.
                    </p>

                    <div className="rd-grammar-box">
                        <div className="rd-grammar-label">Example Grammar</div>
                        <div className="rd-grammar-rules">
                            <div className="rd-grammar-rule">
                                <span className="rd-nt">X</span>
                                <span className="rd-arrow">→</span>
                                <span className="rd-terminal">char</span> <span className="rd-nt">Y</span>
                            </div>
                            <div className="rd-grammar-rule">
                                <span className="rd-nt">Y</span>
                                <span className="rd-arrow">→</span>
                                <span className="rd-terminal">+</span> <span className="rd-terminal">char</span> <span className="rd-nt">Y</span>
                                <span className="rd-pipe">|</span>
                                <span className="rd-epsilon">ε</span>
                            </div>
                        </div>
                    </div>
                </motion.div>

                {/* Procedures */}
                <div className="rd-procedures-grid">
                    {/* Procedure X */}
                    <motion.div
                        className="rd-procedure-card"
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.35 }}
                    >
                        <div className="rd-procedure-header">
                            <div className="rd-procedure-name">
                                <span className="rd-keyword">Procedure</span>
                                <span className="rd-fname">X</span>
                            </div>
                            <span className="rd-procedure-badge main">Main</span>
                        </div>
                        <div className="rd-code-block">
                            <span className="rd-line">{`{`}</span>
                            <span className="rd-line rd-indent-1"><span className="kw">if</span> <span className="var">lookahead</span> <span className="op">=</span> <span className="str">char</span></span>
                            <span className="rd-line rd-indent-1">{`{`}</span>
                            <span className="rd-line rd-indent-2"><span className="fn">Match</span>(<span className="str">char</span>);</span>
                            <span className="rd-line rd-indent-2"><span className="fn">Y</span>();</span>
                            <span className="rd-line rd-indent-1">{`}`}</span>
                            <span className="rd-line rd-indent-1"><span className="kw">else</span></span>
                            <span className="rd-line rd-indent-2"><span className="err">Error</span>();</span>
                            <span className="rd-line rd-indent-1"><span className="kw">if</span> <span className="var">lookahead</span> <span className="op">=</span> <span className="str">$</span></span>
                            <span className="rd-line rd-indent-1">{`{`}</span>
                            <span className="rd-line rd-indent-2"><span className="success">Declare success;</span></span>
                            <span className="rd-line rd-indent-1">{`}`}</span>
                            <span className="rd-line rd-indent-1"><span className="kw">else</span></span>
                            <span className="rd-line rd-indent-2"><span className="err">Error</span>();</span>
                            <span className="rd-line">{`}`}</span>
                        </div>
                    </motion.div>

                    {/* Procedure Y */}
                    <motion.div
                        className="rd-procedure-card"
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.45 }}
                    >
                        <div className="rd-procedure-header">
                            <div className="rd-procedure-name">
                                <span className="rd-keyword">Procedure</span>
                                <span className="rd-fname">Y</span>
                            </div>
                            <span className="rd-procedure-badge main">Recursive</span>
                        </div>
                        <div className="rd-code-block">
                            <span className="rd-line">{`{`}</span>
                            <span className="rd-line rd-indent-1"><span className="kw">if</span> <span className="var">lookahead</span> <span className="op">=</span> <span className="str">'+'</span></span>
                            <span className="rd-line rd-indent-1">{`{`}</span>
                            <span className="rd-line rd-indent-2"><span className="fn">Match</span>(<span className="str">'+'</span>);</span>
                            <span className="rd-line rd-indent-2"><span className="kw">if</span> <span className="var">lookahead</span> <span className="op">=</span> <span className="str">char</span></span>
                            <span className="rd-line rd-indent-2">{`{`}</span>
                            <span className="rd-line rd-indent-3"><span className="fn">Match</span>(<span className="str">char</span>);</span>
                            <span className="rd-line rd-indent-3"><span className="fn">Y</span>(); <span className="cmt">// recursive call</span></span>
                            <span className="rd-line rd-indent-2">{`}`}</span>
                            <span className="rd-line rd-indent-2"><span className="kw">else</span></span>
                            <span className="rd-line rd-indent-3"><span className="err">Error</span>();</span>
                            <span className="rd-line rd-indent-1">{`}`}</span>
                            <span className="rd-line rd-indent-1"><span className="kw">else</span></span>
                            <span className="rd-line rd-indent-2"><span className="cmt">NULL;</span> <span className="cmt">// ε production</span></span>
                            <span className="rd-line">{`}`}</span>
                        </div>
                    </motion.div>

                    {/* Procedure Match */}
                    <motion.div
                        className="rd-procedure-card"
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.55 }}
                    >
                        <div className="rd-procedure-header">
                            <div className="rd-procedure-name">
                                <span className="rd-keyword">Procedure</span>
                                <span className="rd-fname">Match</span>
                                <span className="rd-params">(token t)</span>
                            </div>
                            <span className="rd-procedure-badge helper">Helper</span>
                        </div>
                        <div className="rd-code-block">
                            <span className="rd-line">{`{`}</span>
                            <span className="rd-line rd-indent-1"><span className="kw">if</span> <span className="var">lookahead</span> <span className="op">=</span> <span className="var">t</span></span>
                            <span className="rd-line rd-indent-2"><span className="var">lookahead</span> <span className="op">=</span> <span className="fn">next_token</span>;</span>
                            <span className="rd-line rd-indent-1"><span className="kw">else</span></span>
                            <span className="rd-line rd-indent-2"><span className="err">Error</span>();</span>
                            <span className="rd-line">{`}`}</span>
                        </div>
                    </motion.div>

                    {/* Procedure Error */}
                    <motion.div
                        className="rd-procedure-card"
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.65 }}
                    >
                        <div className="rd-procedure-header">
                            <div className="rd-procedure-name">
                                <span className="rd-keyword">Procedure</span>
                                <span className="rd-fname">Error</span>
                            </div>
                            <span className="rd-procedure-badge error-badge">Error</span>
                        </div>
                        <div className="rd-code-block">
                            <span className="rd-line">{`{`}</span>
                            <span className="rd-line rd-indent-1"><span className="fn">print</span> (<span className="str">"Error"</span>);</span>
                            <span className="rd-line">{`}`}</span>
                        </div>
                    </motion.div>
                </div>
            </div>

            <div className="rd-bottom-spacer" />
        </div>
    );
};

export default RecursiveDescent;
